### ISSUE TITLE
error when Testing GEM5 

### ISSUE THREAD

**Issue by Eason19960910** [zslwyuan/PAAS_V1.0#1]
hey~
I've encountered a weird problem.When I tested GEM5 using 

`build/X86/gem5.opt configs/tutorial/simple.py` 

An error reminded that there are something wrong in the *.py under the tutorial folder.

> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/embedded/paas/PAAS_V1.0-master/src/python/m5/main.py", line 400, in main
    exec filecode in scope
  File "configs/tuturial/1.py", line 19, in <module>
    system.mem_ctrl = DDR3_1600_8x8()
NameError: name 'DDR3_1600_8x8' is not defined

Having tested a few *.py files under the tutorial folder,there are always some strange problems. 
Like `AttributeError: Not allowed to set pio on 'SimObjectVector'`

But when I ran `sudo build/X86/gem5.opt  configs/example/se.py -c tests/test-progs/hello/bin/x86/linux/hello`
It seems like everything is OK....

So what should I do to resolve it?

Btw,I use g++4.8 python 2.7 with ubuntu 16.04.

Thank you.

**Comment by zslwyuan** [comment]
So sorry that I missed this issue. I am not sure whether you have solved the problem but I retry the script in my system and it works fine. However, I cannot find you "1.py" file in the directory "/tuturial". Besides, I guess you should use "DDR3_1600_x64" instead of "DDR3_1600_8x8". You can find all the available types of DDR in "src/mem/DRAMCtrl.py". Hope...it helps though I guess you have figured it out T_T
